###################
# style settings

style:
  link_color:  green      # '#8b0000'    # use ruby-ish red


########################
# build settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: expanded

exclude:
- README.md
- .gitignore
- Gemfile
- Gemfile.lock


plugins:
- jekyll-remote-theme

remote_theme: yukimotopress/jekyll-books-theme
