###################
# site / style settings

title:  Yuki & Moto Press - Free Books about Ruby 'n' Friends
## use &amp; for html??  why? why not??
##   e.g. Yuki &amp; Moto Press - Free Books about Ruby n Friends

home:
  url:   http://yukimotopress.github.io     ## allow http:// and https:// w/ // works??
  title: Yuki & Moto Press


style:
  link_color: '#8b0000'    # use ruby-ish red


########################
# build settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: expanded

exclude:
- README.md
- .gitignore
- Gemfile
- Gemfile.lock
- NOTES.md


plugins:
- jekyll-remote-theme

remote_theme: octobook/books-twentyeighteen-theme
